package uz.ultimatedevs.kattabozortest.utils.exception

class UnknownErrorException(_message: String = "Unknown Error") :
    Throwable(_message)